# Generated by Django 3.2 on 2021-05-04 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imgdb', '0002_auto_20210503_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='viewers',
            field=models.ManyToManyField(related_name='user_accessible_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
