# Generated by Django 3.2 on 2021-05-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgdb', '0003_alter_imagedata_viewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
