# Generated by Django 3.2 on 2021-05-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgdb', '0004_auto_20210509_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='name',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
